apiVersion: v2
description: Kubernetes logging stack with OpenSearch
name: kubernetes-logging
version: 4.3.2
maintainers:
  - name: Niki Dokovski
    email: nickytd@gmail.com
    url: https://github.com/nickytd