{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  clusterIP: None  
  ports:
  - port: 9092
    name: kafka
  - port: 9093
    name: broker
  selector: {{ include "logging.selectorLabels" . | indent 4 }}
    type: kafka
{{ range $kafkaId := until (.Values.kafka.replicas | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-kafka-{{ $kafkaId }}
  labels: {{ include "logging.labels" $ | indent 4 }}
spec:
  ports:
    - port: 9092
      name: kafka
    - port: 9093
      name: broker
    - port: 12345
      name: jmx
  selector: {{ include "logging.selectorLabels" $ | indent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-kafka-{{ $kafkaId }}
    type: kafka
{{ end }}
{{- end }}