{{ if .Values.journalbeat.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-journalbeat-config
  labels:
{{- include "logging.labels" . | indent 2}}
data:
  journalbeat.yml: |-
    logging.level: warning

    journalbeat.inputs:
    # Paths that should be crawled and fetched. Possible values files and directories.
    # When setting a directory, all journals under it are merged.
    # When empty starts to read from local journal.
    # Position to start reading from journal. Valid values: head, tail, cursor
    - paths: ["{{ .Values.journalbeat.path }}"]
      seek: cursor

    tags: ["journalbeat"]
    
    processors:
    - add_id: ~
    - add_kubernetes_metadata:
        in_cluster: true
    #- fingerprint:
    #    fields: ["@timestamp", "@metadata._id"]
    #    ignore_missing: true      

    output.kafka:
      enabled: {{ printf "%t" .Values.kafka.enabled }}
      hosts: ["kafka-svc.{{ .Release.Namespace }}:9092"]
      topic: 'journals'
      partition.hash:
        reachable_only: true
      required_acks: 1
      max_message_bytes: 15728640
      client_id: "${HOSTNAME}"

    output.console:
      enabled: false
      pretty: true

    output.logstash:
      enabled: {{ printf "%t" (not .Values.kafka.enabled) }}
      hosts: ["{{ .Release.Name}}-logstash-indexer:5045"]    
{{ end }}